version: '3.8'

services:
  # Playwright MCP Server
  playwright-mcp:
    build:
      context: ./playwright-mcp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PLAYWRIGHT_MCP_OUTPUT_DIR=/tmp/playwright-output
    networks:
      - crew-network
    volumes:
      - playwright-output:/tmp/playwright-output
    # Run in headless mode with HTTP transport for Docker
    command: ["--headless", "--browser", "chromium", "--no-sandbox", "--port", "3000"]

  # CrewAI Application
  crewai-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CALENDLY_LINK=${CALENDLY_LINK:-https://calendly.com/your-handle/30min}
      - MCP_SERVER_URL=http://playwright-mcp:3000
      - TIMEZONE=${TIMEZONE:-America/New_York}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - playwright-mcp
    networks:
      - crew-network
    volumes:
      - .:/app
    stdin_open: true
    tty: true

networks:
  crew-network:
    driver: bridge

volumes:
  playwright-output:
