version: '3.8'

services:
  # Playwright MCP Server (you'll need to configure this based on your setup)
  playwright-mcp:
    image: playwright-mcp:latest  # Replace with your actual MCP server image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - crew-network
    # Uncomment and modify based on your MCP server setup
    # volumes:
    #   - ./mcp-config:/app/config
    # command: ["node", "server.js"]

  # CrewAI Application
  crewai-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CALENDLY_LINK=${CALENDLY_LINK:-https://calendly.com/your-handle/30min}
      - MCP_SERVER_URL=http://playwright-mcp:3000
      - TIMEZONE=${TIMEZONE:-America/New_York}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - playwright-mcp
    networks:
      - crew-network
    volumes:
      - .:/app
    stdin_open: true
    tty: true

networks:
  crew-network:
    driver: bridge
